plugins: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'app/components/bali/*/preview.rb'
    - 'app/components/bali/*/*/preview.rb'
    - 'coverage/**/*'
    - 'log/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/bali_tasks.rake'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/bin/*'
    - 'spec/dummy/config/**/*'
    - 'spec/dummy/db/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Layout/SpaceBeforeBrackets:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/dummy/app/controllers/**/*'
    - 'lib/bali/form_builder/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'spec/dummy/app/controllers/**/*'
    - 'lib/bali/form_builder/**/*'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/dummy/app/controllers/**/*'

Metrics/ParameterLists:
  Max: 6
  Exclude:
    - 'app/components/bali/side_menu/**/*'
    - 'app/components/bali/card/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'spec/dummy/app/controllers/**/*'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'lib/bali/form_builder/**/*'

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'it', 'before', 'included']
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*'
    - 'spec/dummy/app/controllers/**/*'

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/Lambda:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Exclude:
    - 'spec/dummy/**/*'

Naming/VariableNumber:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Exclude:
    - app/components/**/*
