plugins: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'app/components/bali/*/preview.rb'
    - 'coverage/**/*'
    - 'log/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/bali_tasks.rake'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/bin/*'
    - 'spec/dummy/config/**/*'
    - 'spec/dummy/db/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/SpaceBeforeBrackets:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/Lambda:
  Enabled: false

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'it', 'before', 'included']
  Exclude:
    - spec/*
    - lib/tasks/*

Naming/VariableNumber:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Exclude:
    - app/components/**/*

Style/RedundantBegin:
  Enabled: false
