# frozen_string_literal: true

# One person's dashboard arrangement: which widgets, in what order, at what size.
#
# CHECKED IN so `bin/rails db:migrate` on a fresh clone builds a working demo at
# /dashboard_widgets. A real host installs it instead with
# `bin/rails bali:install:migrations:dashboard_widgets`, which copies this same
# file and renumbers it to the moment of the install.
#
# KEPT AT THE ENGINE'S OWN TIMESTAMP rather than renumbered, and that is
# load-bearing: `db/schema.rb` is stamped `2026_08_25_120000`, so `db:schema:load`
# marks this version migrated and leaves nothing pending. Renumber it to `now` and
# a developer who loads the schema — which is what CI and `bin/setup` do — is then
# offered a pending migration that fails on a table that already exists.
#
# `owner` is polymorphic because the engine cannot know whether a host's user is
# a `User`, a `Member` or an `Employee` — which is also why the table named for
# one of them would be a lie, and why there is no foreign key pointing into the
# host's schema.
#
# These rows NEVER grant visibility. `Bali::DashboardWidget::Store` is handed the set the
# owner is already authorized for and can only subset and reorder it.
class CreateBaliDashboardWidgets < ActiveRecord::Migration[7.0]
  def change
    create_table :bali_dashboard_widgets do |t|
      # index: false — the unique index below leads with [owner_type, owner_id]
      # and serves every lookup, so the references default would be redundant.
      t.references :owner, polymorphic: true, null: false, index: false

      # The host's scope for this dashboard — a tenant id, or "" for a
      # single-tenant app. NOT NULL with a default rather than nullable: Postgres
      # treats NULLs as DISTINCT in a unique index, so a nullable column would
      # let a single-tenant host store the same widget twice.
      t.string :context, null: false, default: ""

      # Which dashboard, for a host with more than one ("today", "finance").
      t.string :dashboard_key, null: false

      t.string :widget_key, null: false
      t.integer :position, null: false

      # Nullable on purpose: "no opinion", so the widget renders at the size it
      # was drawn around. A row predating a resize still renders. Limited to
      # 32 rather than left at Postgres's default 255: `Bali::Widget::SIZES`
      # names are short, `Bali::Widget::Placement` resolves a name it does not
      # recognise back to the widget's default, and the cap only guards against
      # an authenticated user inflating their own rows — so it can afford to be
      # generous rather than exact. Real only on an adapter that enforces column
      # length: SQLite's type affinity ignores it entirely.
      t.string :size, limit: 32

      t.timestamps
    end

    # Short names: the autogenerated ones for five columns overrun PostgreSQL's
    # 63-character identifier limit.
    add_index :bali_dashboard_widgets,
              %i[owner_type owner_id context dashboard_key widget_key],
              unique: true, name: "index_bali_dashboard_widgets_uniqueness"
    add_index :bali_dashboard_widgets,
              %i[owner_type owner_id context dashboard_key position],
              name: "index_bali_dashboard_widgets_ordering"
  end
end
