# frozen_string_literal: true

# One person's dashboard arrangement: which widgets, in what order, at what size.
# A host installs this with `bin/rails bali:install:migrations:dashboard_widgets`.
#
# `owner` is polymorphic because the engine cannot know whether a host's user is
# a `User`, a `Member` or an `Employee` — which is also why the table named for
# one of them would be a lie, and why there is no foreign key pointing into the
# host's schema.
#
# These rows NEVER grant visibility. `Bali::Widget::Layout` is handed the set the
# owner is already authorized for and can only subset and reorder it.
class CreateBaliDashboardWidgets < ActiveRecord::Migration[7.0]
  def change
    create_table :bali_dashboard_widgets do |t|
      # index: false — the unique index below leads with [owner_type, owner_id]
      # and serves every lookup, so the references default would be redundant.
      t.references :owner, polymorphic: true, null: false, index: false

      # The host's scope for this dashboard — a tenant id, or "" for a
      # single-tenant app. NOT NULL with a default rather than nullable: Postgres
      # treats NULLs as DISTINCT in a unique index, so a nullable column would
      # let a single-tenant host store the same widget twice.
      t.string :context, null: false, default: ""

      # Which dashboard, for a host with more than one ("today", "finance").
      t.string :dashboard_key, null: false

      t.string :widget_key, null: false
      t.integer :position, null: false

      # Nullable on purpose: "no opinion", so the widget renders at the size it
      # was drawn around. A row predating a resize still renders.
      t.string :size

      t.timestamps
    end

    # Short names: the autogenerated ones for five columns overrun PostgreSQL's
    # 63-character identifier limit.
    add_index :bali_dashboard_widgets,
              %i[owner_type owner_id context dashboard_key widget_key],
              unique: true, name: "index_bali_dashboard_widgets_uniqueness"
    add_index :bali_dashboard_widgets,
              %i[owner_type owner_id context dashboard_key position],
              name: "index_bali_dashboard_widgets_ordering"
  end
end
