# frozen_string_literal: true

# One person's dashboard arrangement: which widgets, in what order, at what size.
# A host installs this with `bin/rails bali:install:migrations:dashboard_widgets`.
#
# `owner` is polymorphic because the engine cannot know whether a host's user is
# a `User`, a `Member` or an `Employee` — which is also why the table named for
# one of them would be a lie, and why there is no foreign key pointing into the
# host's schema.
#
# These rows NEVER grant visibility. `Bali::DashboardWidget::Store` is handed the set the
# owner is already authorized for and can only subset and reorder it.
class CreateBaliDashboardWidgets < ActiveRecord::Migration[7.0]
  def change
    create_table :bali_dashboard_widgets do |t|
      # index: false — the unique index below leads with [owner_type, owner_id]
      # and serves every lookup, so the references default would be redundant.
      t.references :owner, polymorphic: true, null: false, index: false

      # The host's scope for this dashboard — a tenant id, or "" for a
      # single-tenant app. NOT NULL with a default rather than nullable: Postgres
      # treats NULLs as DISTINCT in a unique index, so a nullable column would
      # let a single-tenant host store the same widget twice.
      t.string :context, null: false, default: ""

      # Which dashboard, for a host with more than one ("today", "finance").
      t.string :dashboard_key, null: false

      t.string :widget_key, null: false
      t.integer :position, null: false

      # NULLABLE, BUT NOT WRITTEN NULL BY BALI. Every writer persists a concrete
      # name: `Bali::Widget::Placement` resolves an omitted or retired size to
      # the widget's `default_size` at construction, and `Store#row_for` stores
      # what it resolved. So an arrangement is FROZEN at the sizes its owner was
      # shown — changing a widget's `default_size` later moves new dashboards and
      # leaves existing ones alone, deliberately: a layout must not rearrange
      # itself under someone because a library was upgraded.
      #
      # Nullable anyway, for the two cases Bali does not write: a row predating
      # this column, and a host calling `Store#arrange` against its own table
      # without one. Both still render — `Placement` falls back — which is why
      # this stayed a nullable column rather than becoming NOT NULL.
      #
      # Limited to 32 rather than left at Postgres's default 255: `Bali::Widget::SIZES`
      # names are short, `Bali::Widget::Placement` resolves a name it does not
      # recognise back to the widget's default, and the cap only guards against
      # an authenticated user inflating their own rows — so it can afford to be
      # generous rather than exact. Real only on an adapter that enforces column
      # length: SQLite's type affinity ignores it entirely.
      t.string :size, limit: 32

      t.timestamps
    end

    # Short names: the autogenerated ones for five columns overrun PostgreSQL's
    # 63-character identifier limit.
    add_index :bali_dashboard_widgets,
              %i[owner_type owner_id context dashboard_key widget_key],
              unique: true, name: "index_bali_dashboard_widgets_uniqueness"
    # `widget_key` LAST, matching `scope :ordered`'s `order(:position, :widget_key)`.
    # The tie-break is not decoration: a row for a widget the owner cannot see
    # keeps its position while the visible ones renumber around it, so two rows
    # can share a position and Postgres would otherwise return them in an
    # arbitrary order — making `stored_keys` nondeterministic and `choose`'s
    # "survivors keep their stored order" guarantee unstable. An index that stops
    # at `position` cannot serve that sort.
    add_index :bali_dashboard_widgets,
              %i[owner_type owner_id context dashboard_key position widget_key],
              name: "index_bali_dashboard_widgets_ordering"
  end
end
