name: Rubocop
on:
  push:
    branches: [main, "3.0"]
  pull_request:
    branches: [main, "3.0"]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
